### ISSUE TITLE
Problems with caching

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#177]
A new deployment may cause caching issues.

**Comment by Ollitod** [comment]
The team encounters this issue every time the site is loaded in a new tab. However, after reloading the tab (F5), the new version is displayed. There debugger shows nothing in the cache. Furthermore, this issue seems to occur only in Firefox. If site is requested in Incognito-Mode of Firefox, the correct version is displayed. A test in Google Chrome confirms our assumption.

**Comment by cchet** [comment]
We should check if we have proper html meta tags (Cache-Control) defined. Normally the frontend build should produce unique filenames which have an unique hash added, so we should not face caching issues. Maybe the browsers do cache the whole site not only the javascript files.
