### ISSUE TITLE
MEGA 2.0 is really slow (ZEP?)

### ISSUE THREAD

**Issue by sthausmann** [Gepardec/mega#268]
Siehe #410

**Comment by WernerBruckmueller** [comment]
In PL view kann Freigabedatum entfernt werden, sofern es für die Performance etwas hilft.

**Comment by cchet** [comment]
This behaviour is caused by the reload of the page which involves a ZEP SOAP call which is knowingly very slow.
I think we don't need to constantly load the 'freigabeDatum' from ZEP, I think we can calculate it based on the current active month or at least load it ones and not on each little action on the page.
