### ISSUE TITLE
Fehler beim Erstellen eines Kommentars

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#469]
Über die PM-View wurde ein Kommentar bei Chris hinzugefügt (er hatte bereits ein Kommentar vom Vormonat). Dabei ist ein Internet Fehler 500 passiert.
Das Kommentar wurde übernommen.
![image](https://user-images.githubusercontent.com/16414159/127970061-3023df9f-584e-4cd5-929f-ddbcd63abff7.png)
![image](https://user-images.githubusercontent.com/16414159/127970142-eff9f6c1-e3a1-4140-b5c8-f202fa349720.png)

Soll:
Kein Fehler

**Comment by Ruhsi** [comment]
Caused by: javax.validation.ConstraintViolationException: Validation failed for classes [com.gepardec.mega.db.entity.employee.Comment] during persist time for groups [javax.validation.groups.Default, ]
--
ConstraintViolationImpl{interpolatedMessage='L?nge muss zwischen 1 und 500 sein', propertyPath=message, rootBeanClass=class com.gepardec.mega.db.entity.employee.Comment, messageTemplate='{org.hibernate.validator.constraints.Length.message}'}
]

@WernerBruckmueller das Kommentar sieht nicht aus als wäre es länger als 500 Zeichen, oder?

**Comment by phiwu-gpdec** [comment]
@Ollitod und @patholzer könnt ihr auch das bitte ansehen?
