### ISSUE TITLE
Role-Configuration

### ISSUE THREAD

**Issue by WernerGepardec** [Gepardec/mega#57]
Precondition:
UX as described in issue #58

As a ZEP-Admin user, I want to assign roles to all existing ZEP-users. This is necessary to configure reminder behavior.

The following roles should be available:
- Mitarbeiter (default)
- Projektleitung
- Office Management

The MEGA users have to be in sync with the users used in ZEP.

DoD

- [ ] Any user can have multiple roles
- [ ] New users have the default options and are added automatically.
- [ ] The admin (ZEP-role) can manage the user accounts
- [ ] Users that were removed but still count as 'valid' due to the Beschäftigungszeitraum shall be shown in the Admin interface/dashboard

To discuss with dev:
- [ ] New users should be added automatically (e.g. minimum daily)

**Comment by mml-gepardec** [comment]
We should evaluate the possibilities for the creating and managing such roles (add database to the backend, manage roles in keycloak?)

**Comment by mml-gepardec** [comment]
As discussed:
Since the "roles" are supposed to be used for notifications Keycloak will not be used for this kind of "role configuration".
ZEP is master for the project roles so the mail addresses for notifications will be retrieved via SOAP and a special handling for "Office Management" will be in place.
No need for a persistence layer!

**Comment by WernerGepardec** [comment]
Issue is deprecated!!!
See #79
